---
title: "LabTest"
output: html_document
---

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

<div class="row" style="padding-top: 30px;">


# Executive Summary 

In recent years, the prices of condominiums have skyrocketed, which has caused various problems for individuals that seek to find their new dream home. This pattern is also evident for the average square meter price in Aarhus C, leaving people with little to no option to know if a seller's proposition is fair. The motivation for this paper is to investigate feature importance and the behavior of the condominiums market in the central part of Aarhus. The purpose is to build machine- and deep learning models with the objective of predicting a best guess for today's sales price given data from the period 2018-2021. This acts as an unbiased estimate for people, looking for a new condominium in the city center. In conclusion, the best three models developed in this paper are: Extreme Gradient Boosting with a MAE at 231,363 DKK, Random Forest with a MAE at 224,218 DKK, and a superior Neural Network model with a MAE as low at 24,787 DKK. Thus, by utilizing the latter model, it is possible to obtain a reliable second opinion.


```{r, echo=FALSE}
library(readxl)
m2pris <- read_excel("data/m2pris.xlsx")

m2pris$...1 <- gsub("K2",".25", m2pris$...1)
m2pris$...1 <- gsub("K3",".50", m2pris$...1)
m2pris$...1 <- gsub("K4",".75", m2pris$...1)

m2pris$...1 <- as.numeric(m2pris$...1)

library(dygraphs)
dygraph(m2pris, main = "Square meter prices") %>% 
  dyRangeSelector(dateWindow = c("1992", "2021")) %>% 
  dyLegend(show = "follow")
```




</div>
<div class="col-sm-6">


